---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: default
---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: external-dns
    namespace: default
  rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"] 
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch","list","get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.8.0
        args:
        - --source=ingress  # or ingress or both
        - --source=service
        - --provider=akamai
        - --domain-filter={{ DOMAIN }} #smu-labs.cl
        # zone-id-filter may be specified as well to filter on contract ID
        - --registry=txt
        - --txt-owner-id={{ CLUSTER_NAME }}  #huawei-santiago-factory-front-develop
        - --txt-prefix=_txt_
        - --log-level=trace
        env:
          EXTERNAL_DNS_AKAMAI_SERVICECONSUMERDOMAIN: ${{ secrets.EXTERNAL_DNS_AKAMAI_SERVICECONSUMERDOMAIN }}
          EXTERNAL_DNS_AKAMAI_CLIENT_TOKEN: ${{ secrets.EXTERNAL_DNS_AKAMAI_CLIENT_TOKEN }}
          EXTERNAL_DNS_AKAMAI_CLIENT_SECRET: ${{ secrets.EXTERNAL_DNS_AKAMAI_CLIENT_SECRET }}
          EXTERNAL_DNS_AKAMAI_ACCESS_TOKEN: ${{ secrets.EXTERNAL_DNS_AKAMAI_ACCESS_TOKEN }}

